version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql-library-db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - library_data:/var/lib/mysql

  spring-library:
    image: app
    ports:
      - "8080:8080"
    networks:
      - library
    depends_on:
      - db

volumes:
  library_data:
